-- AlterTable
ALTER TABLE `LifecycleLog` MODIFY `action` ENUM('CREATED', 'ALLOCATED', 'RETURNED', 'TRANSFERRED', 'UPGRADED', 'MAINTENANCE_START', 'MAINTENANCE_DONE', 'SCRAPPED', 'REPLACED') NOT NULL;
